-- MySQL Script generated by MySQL Workbench
-- Tue Sep 16 17:13:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema meufreela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema meufreela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meufreela` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
USE `meufreela` ;

-- -----------------------------------------------------
-- Table `meufreela`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meufreela`.`usuario` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `tipo_usuario` ENUM('freelancer', 'voluntario', 'ambos') NOT NULL,
  `data_cadastro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `meufreela`.`vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meufreela`.`vaga` (
  `id` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `tipo_vaga` ENUM('freela', 'voluntaria') NOT NULL,
  `remuneracao` DECIMAL(10,2) NULL DEFAULT NULL,
  `local` ENUM('remoto', 'presencial') NOT NULL,
  `data_publicacao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `data_limite` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario` (`id_usuario` ASC),
  CONSTRAINT `vaga_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `meufreela`.`usuario` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `meufreela`.`candidatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meufreela`.`candidatura` (
  `id` INT(11) NOT NULL,
  `id_vaga` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `data_candidatura` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('pendente', 'aprovado', 'recusado') NULL DEFAULT 'pendente',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_vaga` (`id_vaga` ASC, `id_usuario` ASC),
  INDEX `id_usuario` (`id_usuario` ASC),
  CONSTRAINT `candidatura_ibfk_1`
    FOREIGN KEY (`id_vaga`)
    REFERENCES `meufreela`.`vaga` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `candidatura_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `meufreela`.`usuario` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
